services:
  - type: web
    name: suffernotgamesworkshop
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
