services:
  - type: web
    name: suffernotgamesworkshop
    runtime: docker
    dockerfilePath: ./Dockerfile
    branch: main
    autoDeploy: true
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
