spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop
    username: workshop
    password: workshop
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
